### ISSUE TITLE
APK size due to material-icons-extended dependency

### ISSUE THREAD

**Issue by nelletto** [appcues/appcues-android-sdk#651]
Hi, we recently noticed an increase in the size of our application's debug build by about 6 MB, we looked at dependencies and found `androidx.compose.material:material-icons-extended` required by AppCues. On [developer.android.com](https://developer.android.com/reference/kotlin/androidx/compose/material/icons/package-summary) we read 

> contains the full set of Material icons. Due to the very large size of this library, make sure to use R8/Proguard to strip unused icons if you are including this library as a direct dependency

We use R8 to do the release build and we have a doubt that there may be problems by removing the resources.
It seems strange to us that this dependency is needed, is it a bug?

**Comment by andretortolano** [comment]
thank you @nelletto for bringing this issue, we overlooked this new inclusion on the project, we actually prefer not including extra dependencies whenever possible since we can conflict with your versions, we actually want two Material icons or similar so we decided to remove the library and manually import the Icons to use it in our Debugger. 

#652 is the change proposed here, hopefully that will look better on your end after we publish this small patch.

That said are you on Native android SDK, Segment or any of the x-platforms, so we can plan the patch fix for you.
